### ISSUE TITLE
Player can use multiple weapon types

### ISSUE THREAD

**Issue by camgrodgers** [camgrodgers/senior-fps#100]
- [X] There should be a system for the player to switch between weapons using the number keys or maybe scroll wheel. This could be implemented as a Half-life style inventory or maybe weapon slots like FEAR. Half-life style is easier. #129
- [X] There should be weapon drops from enemies and crates to enable the player to use a specific weapon (which will be disabled until they pick it up)  #135 

The player should have:
- [x] sniper rifle #143
- [X] pistol  #129
- [x] semi-auto rifle #126

Out of scope due to time constraint:
~~- [ ] grenades~~
~~- [ ] smoke grenades~~
~~- [ ] HUD display for weapon switching~~
