### ISSUE TITLE
Play-testing survey issues (player suggestions)

### ISSUE THREAD

**Issue by camgrodgers** [camgrodgers/senior-fps#133]
- [x] lack of measured progress such as "enemies defeated" or "time survived" -- achieved through level beating progress
- [X] Show enemies shooting at player and missing #136
- [X] mouse sensitivity too high/mouse sensitivity slider needed #130
- [X] Player aim too accurate (needs variance based on motion, firing rate etc) #116 #117
- [X] Needs reloading mechanics #120
- [X] Shouldn't slide off ramps #123
- [X] enemy location indicators #114

Shelved due to scope / time constraints:
~~- [ ] Headshot mechanics~~
