### ISSUE TITLE
Varied AI behaviors

### ISSUE THREAD

**Issue by camgrodgers** [camgrodgers/senior-fps#97]
There should be a variety of AI behaviors. This issue consists of separate sub-issues for each behavior:

- [X] spreading out so they don't block each other's aim at the player #183
- [X] hearing noises the player makes and investigating them #173
- [x] Attempting to run away or hide when low on health, or when all the other enemies are dead #183
- [X] Moving to get within optimal range of the player #183
- [x] throwing grenades to flush player out #156
- [x] reduced visibility from bushes, smoke grenades
- [x] crouching behind certain cover objects #65  #150
- [x] shooting at the player but missing #136
- [x] flanking (happens as a side effect of node layout, as in FEAR)

Shelved behavior ideas due to being out of scope/out of time:
~~- [ ] Running away from things that are about to explode~~
~~- [ ] killing shots when the player is at 100% danger~~
~~- [ ] squad tactics~~
~~- [ ] wounded state in which enemies lie on the ground but aren't dead~~
~~- [ ] assisting wounded comrades~~
