### ISSUE TITLE
Level design

### ISSUE THREAD

**Issue by camgrodgers** [camgrodgers/senior-fps#99]
We should experiment with a variety of level designs. Things to try:
- [x] closed-off areas like in FEAR
- [x] semi-open areas like STALKER, Crysis, MGSV
- [x] There should be a tutorial level: #103 #181

Tooling for level design should be improved, with things like:

- [X] System to have levels unlock as the player beats previous levels -- shelving this for grader testing purposes, but it'd be easy to add as level progress has been added #176
- [X] Message popup objects that can work in a tutorial #110 #174
- [x] Finish markers to signal that a level was completed #158
- [X] Item spawn nodes that persist items through level reload #158
- [X] improve normal navnodes  #147
- [x] scenes for common objects such as crates, chest-high walls, pillars with built-in nav nodes  #111  #145
- [X] improved patrol route nodes  #90
- [X] bushes or grass that the player can hide in  #144
- [X] enemy spawn triggers #146
